export const UNIV_AUTH = {
  TITLE: '학교 인증',
  EMAIL: '이메일',
  EMAIL_INFO: '학교 메일을 사용해주세요.',
  AUTH_CODE: '인증번호',
  EMAIL_BTN: '인증번호 전송',
  EMAIL_REBTN: '인증번호 재전송',
  EMAIL_SUCCESS: '인증번호 발송이 완료되었습니다!',
  EMAIL_FAIL: '이메일을 다시 확인해주세요!',
  EMAIL_EXIST: '이미 사용중인 이메일입니다!',
  AUTH_CODE_BTN: '인증번호 확인',
  WRONG_CODE: '인증번호가 잘못되었습니다!',
  SUCCESS_CODE: '인증 되었습니다!',
  SERVICE_TERMS: '서비스 정책',
  SERVICE_TERMS_INFO: '정보 제공 동의',
  SEE_TERMS: '내용보기',
  BTN: '확인',
} as const;

const GRADE_LIST = ['1학년', '2학년', '3학년', '4학년'] as const;

const MAJOR_LIST = [
  '경영학전공',
  '글로벌경영학전공',
  '회계세무학전공',
  '금융수학전공',
  '빅데이터경영전공',
  '미디어커뮤니케이션학과',
  '관광경영학과',
  '경제학과',
  '의료산업경영학과',
  '응용통계학과',
  '사회복지학과',
  '유아교육학과',
  '심리학과',
  '패션산업학과',
  '한국어문학과',
  '영미어문학과',
  '유럽어문학과',
  '동양어문학과',
  '법학과',
  '경찰행정학과',
  '행정학과',
  '도시계획학전공',
  '조경학전공',
  '실내건축학전공',
  '건축학전공',
  '건축공학전공',
  '설비소방공학과',
  '화공생명공학전공',
  '배터리공학전공',
  '기계공학전공',
  '산업공학전공',
  '스마트팩토리전공',
  '토목환경공학과',
  '신소재공학과',
  '미래자동차학과',
  '식품생명공학과',
  '식품영양학과',
  '바이오나노학과',
  '생명과학과',
  '물리학과',
  '화학과',
  '전자공학전공',
  '반도체공학전공',
  '차세대반도체설계전공',
  '반도체-디스플레이학과',
  '반도체설계학과',
  '클라우드공학과',
  '소프트웨어전공',
  '인공지능전공',
  '컴퓨터공학전공',
  '스마트보안전공',
  '전기공학과',
  '스마트시티학과',
  '의공학과',
  '바이오의료기기학과',
  '게임·영상학과',
  '한의예과',
  '회화·조소전공',
  '디자인전공',
  '성악전공',
  '기악전공',
  '작곡전공',
  '체육전공',
  '태권도전공',
  '연기예술학과',
  '운동재활학과',
  '자유전공',
  '의예과',
  '약학과',
  '바이오로직스학과',
  '간호학과',
  '치위생학과',
  '방사선학과',
  '물리치료학과',
  '응급구조학과',
] as const;

const DOUBLE_MAJOR_LIST = ['-', ...MAJOR_LIST] as const;

const INTEREST_FIELD_LIST = ['기획', '디자인', '미디어', '예술', 'IT'] as const;

export const USER_INFO = {
  TITLE: '상세 정보 입력',
  NICKNAME: '닉네임',
  NICKNAME_BTN: '중복확인',
  NICKNAME_FAIL: '이미 사용중인 닉네임입니다!',
  NICKNAME_SUCCESS: '사용 가능한 닉네임입니다!',
  GRADE: '학년',
  GRADE_LIST,
  MAJOR: '본전공',
  MAJOR_LIST,
  DOUBLE_MAJOR: '복/부전공',
  DOUBLE_MAJOR_LIST,
  INTEREST_FIELD: '관심분야',
  INTEREST_FIELD_LIST,
  BTN: '가입하기',
} as const;

export const LOGIN_SUCCESS = {
  TITLE: 'WE NEED, WIN IT.',
  TITLE1: '회원가입이 완료되었습니다!',
  TITLE2: '다양한 콘텐츠를 감상해보세요!',
};
